version: 2.1

orbs:
  windows: circleci/windows@2.4

jobs:
  test:
    description: Setup and run application tests
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "SnailRacing.Ralf/SnailRacing.Ralf.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "SnailRacing.Ralf/SnailRacing.Ralf.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet test --blame-hang --blame-hang-timeout 2min -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: /root/project/test_coverage
      - store_artifacts:
          path: /tmp/**.*.dmp
  build:
    description: Build application with Release configuration
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test